{
 "title": "my_dashboards",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "running_container",
   "type": "gauge",
   "description": "shows running container ",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU_usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance) (\r\n    rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory_used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1024-node_memory_MemAvailable_bytes/1024/1024)/1024*100"
    }
   ]
  },
  {
   "title": "Disk_Usages ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/etc/hostname\"} /1024/1024/1024 -node_filesystem_free_bytes{mountpoint=\"/etc/hostname\"}/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}